### ISSUE TITLE
Add html as type of media

### ISSUE THREAD

**Issue by raufrecht** [ShepherdDev/digital-signage#3]
This isn't an issue, but have you looked into being able to use an html page as a type of media? As an example, adding in a weather widget or something we use on our digital displays (that I want to get out of) is an Instagram scroller (https://lightwidget.com/). Your options would then be unlimited .

**Comment by cabal95** [comment]
We had looked at that (well not that widget specifically, but the idea of non-video and non-html screens) and it was going to be very difficult to implement in a way that would transition well. Even the image->video->image transitions are not that great.

What you might be able to do instead is create a webhook or something that generates an image dynamically with the weather widget on it - though you would have to get into some C# or php or somesuch coding at that point.

**Comment by raufrecht** [comment]
Are there any of the transitions that can be used such that you limit the types of transitions that can be used if html is selected?

**Comment by cabal95** [comment]
Every single transition requires an image on both sides (coming in and going out). We cheat with a video by using an all-blank image and then after the transition finishes we quickly swap out the black image for the video. It's clunky but works because nearly every video we use will start black and fade in. Then also fade out to black. We then do the reverse, we swap out the finished video for the black image and then transition to the next slide.

**Comment by cabal95** [comment]
More specifically (kind of glossed over this point but meant to mention it), the library we use to handle the transitions only works with images - and only with images of the exact right resolution.
