### ISSUE TITLE
Ability to deploy block non-fullscreen

### ISSUE THREAD

**Issue by DerekMangrum** [ShepherdDev/digital-signage#4]
We are looking to replace Rise Vision with this plugin. As we have been doing testing, we have come across something that I wanted to ask about.

The /digitalsign Page (the default page) deploys using a 'Blank' template with a single zone and no formatting and everything runs full-screen. 

In our Rise Vision implementation, we have a couple of digital sign locations where they built a custom display. Specifically, the slides will play in a section of the window (right two-thirds, for example) and the left third of the screen has other static content... The top half displays a clock and the bottom half displays a Bible verse/church slogan/etc.

I have tried deploying the block onto another page that has a more complicated template, hoping to replicate a similar experience. But, the block did not render as I would expect (take up all of the Zone the block is in, but leave the rest of the page alone).

I'm no developer, and I assume adding this functionality may prove to be an extensive change. It is not a deal-breaker for us, but being able to be more flexible with the page layout would be a great feature.

If I have missed something and this is possible in some way, I would love to know.

Just wanted to bring this to your attention. I would be happy to discuss this further, if you would like. Thank you.

**Comment by cabal95** [comment]
I’m out of town for a couple days but will look into it more when I get back. I believe however that you would need to override some CSS classes that are used to make it go full screen despite the area made available in the zone.

**Comment by cabal95** [comment]
Hey Derek, sorry it took me longer to get back to you than I had intended.  I did a quick test. There is a CSS class called `dsrContainer` that you will need to override on that page. By default it uses absolute positioning to fill the screen. You will have to adjust those absolute positions, or you might be able to just force the positioning to be normal again. I think I had to do that because even the blank Theme templates had edging on the sides that caused issues with it not presenting nicely in full screen.

**Comment by DerekMangrum** [comment]
Hmmm... Ok. I am not a CSS guy at all. So, gonna have to back-burner this for the time being. I talked with our people who will be using this, and the normal behavior isn't a deal-breaker. So, we will just go with that for now. Thanks!
